### ISSUE TITLE
Create /health endpoint

### ISSUE THREAD

**Issue by toriengler** [CSCI-GA-2820-SP24-001/wishlists#78]
**As a** developer
**I need** a /health endpoint
**So that** Kubernetes knows that our microservice is healthy.

   
 ### Details and Assumptions
*I think we already have this   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that I create a /health endpoint in routes.py
 When I run /health on the api
 Then it should return a {"status":"OK"} and 200_OK return code 
```

**Comment by hp1163** [comment]
We had done this already in a previous sprint: checked for routes.py and test.py for a health endpoint.
